version: 2
    
sources:
  - name: sql_server_dbo
    description: Movie Database Hosted on SQL Server
    freshness:
      warn_after: {count: 12, period: hour}
    loaded_at_field: _fivetran_synced

    tables: 
      - name: movie
      - name: movie_scd2
      - name: movie_cast
      - name: person

models:
  - name: movies_current
    description: "Current Version of All Movies (SCD-4)"
    columns:
        - name: movie_id
          description: "The PK for this table"
          data_tests:
              - unique
              - not_null
